
ALTER SEQUENCE DEPENDENCIES_ID_SEQ RESTART 26;
ALTER SEQUENCE CAMPOS_TEMATICOS_ID_SEQ RESTART 20;
ALTER SEQUENCE CATEGORIAS_ID_SEQ RESTART 16;
ALTER SEQUENCE ROLE_ID_SEQ RESTART 3;
ALTER SEQUENCE USERS_ID_SEQ RESTART 18;
ALTER SEQUENCE VERBETES_ID_SEQ RESTART 915;